# Host: yfsoso.com  (Version: 5.5.37-log)
# Date: 2015-04-28 10:35:16
# Generator: MySQL-Front 5.3  (Build 4.120)

/*!40101 SET NAMES utf8 */;

#
# Structure for table "author"
#

DROP TABLE IF EXISTS `author`;
CREATE TABLE `author` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `updatetime` datetime DEFAULT '0000-00-00 00:00:00',
  `rss` smallint(4) DEFAULT '1' COMMENT '0:主动搜索,1:rss,>1000:link爬取,>2000:onlylink爬取',
  `rate` int(11) NOT NULL DEFAULT '0',
  `name` varchar(20) DEFAULT NULL,
  `url` varchar(128) NOT NULL,
  `rssurl` varchar(128) NOT NULL,
  `failtimes` int(11) NOT NULL DEFAULT '0',
  `cmovietype` varchar(256) DEFAULT NULL COMMENT '(c分类t标题l链接)执行->0未知 1电影 2电视剧 3综艺 4动漫 5纪录片',
  `cmoviecountry` varchar(256) DEFAULT NULL COMMENT '0未知 1华语 2欧美 3日韩 4其他',
  `clinkquality` varchar(256) DEFAULT NULL COMMENT '0未知 1未知 2抢先 3修正 4普清 5高清 6超清 7三维',
  `clinktype` varchar(256) DEFAULT NULL COMMENT '0未知类型 1迅雷资源 2FTP资源 3BT 资源 4磁力链接 5电驴资源 6网盘资源 7网页在线 8百度影音 9快播资源',
  `clinkway` varchar(256) DEFAULT NULL COMMENT '0未知类型 1影视资讯 2热门评论 3预告花絮 4相关活动 5购票链接 6下载链接 7在线观看 8字幕翻译',
  `ctitle` varchar(128) DEFAULT NULL COMMENT '影片名字的提取方法,g是按照模式抽取<c>g%《(.*?)》%0</c>,f是按照模式剔除,x是综合方法<c>x%1%1</c>',
  `clinkdownway` varchar(128) DEFAULT NULL COMMENT '0未知资源 1直接下载 2跳转下载 3登陆下载 4积分下载',
  `clinkvalue` varchar(256) DEFAULT NULL COMMENT '0:不起作用 1新闻消息类 2抢先类 3修正 4普清 5 高清 6超清 7三维',
  `email` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rssurl` (`rssurl`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

#
# Data for table "author"
#

/*!40000 ALTER TABLE `author` DISABLE KEYS */;
INSERT INTO `author` (`rss`, `rate`, `name`, `url`, `rssurl`, `failtimes`, `cmovietype`, `cmoviecountry`, `clinkquality`, `clinktype`, `clinkway`, `ctitle`, `clinkdownway`, `clinkvalue`, `email`) VALUES
(1,0,'海阔天空电影','http://www.12u.cc','http://www.12u.cc/feed',25,'<c>l%ju\\/|gangtai\\/|tv\\/%2</c><c>l%zongyi%3</c><c>l%.*?%1</c>','<c>l%gangtai%1</c><c>l%meiju%2</c><c>l%riju|hanju%3</c><c>t%中国|香港|台湾|大陆|澳门%1</c><c>t%欧美|美国|欧洲|俄罗斯|英国|法国|德国%2</c><c>t%日本|韩国%3</c><c>l%.*?%0</c>','<c>t%TC|TS|抢先%1</c><c>l%\\/3d\\/%6</c><c>t%DVD%3</c><c>t%BD|1280|高清|HD%4</c><c>l%.*?%3</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%0</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'炫电影','http://www.xuandy.com/','http://www.xuandy.com/feed',12,'<c>c%电影%1</c><c>c%剧集|电视%2</c><c>c%综艺%3</c><c>c%动画%4</c><c>l%.*?%1</c>','<c>c%大陆|港台%1</c><c>c%欧美%2</c><c>c%日韩%3</c><c>l%.*?%0</c>','<c>l%.*?%5</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%0</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'新浪电影','http://rss.sina.com.cn/','http://rss.sina.com.cn/ent/film/focus7.xml',8,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'新浪电视','http://rss.sina.com.cn/','http://rss.sina.com.cn/ent/tv/focus7.xml',7,'<c>l%.*?%2</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'搜狐电影','http://rss.yule.sohu.com/rss.shtml','http://rss.yule.sohu.com/rss/dianying.xml',7,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'搜狐电视','http://rss.yule.sohu.com/rss.shtml','http://rss.yule.sohu.com/rss/dianshiqianyan.xml',6,'<c>l%.*?%2</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'影评yp136','http://www.yp136.com/','http://www.yp136.com/feed',12,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%2</c>',NULL),
(1,0,'影评网','http://yingpingwang.com','http://yingpingwang.com/feed',9,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%2</c>',NULL),
(1,0,'时光网电视新闻','http://news.mtime.com','http://feed.mtime.com/tvnews.rss',92,'<c>l%.*?%2</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%1</c><c>g%\"(.*?)\"%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'时光网视频新闻','http://news.mtime.com','http://feed.mtime.com/videonews.rss',90,NULL,NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%1</c><c>g%\"(.*?)\"%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'贼吧网','http://www.zei8.com/','http://www.zei8.com/data/rss/173.xml',937,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>g%【(.*?)】%0</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'时光网电影新闻','http://news.mtime.com','http://feed.mtime.com/movienews.rss',94,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'Cinephilia迷影','http://cinephilia.net','http://cinephilia.net/feed',62,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>c%资讯%1</c><c>c%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'',NULL),
(1,0,'影像日报','http://moviesoon.com/','http://moviesoon.com/news/feed/',77,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%2</c>',NULL),
(1,0,'电影下载','http://www.dy558.com/','http://www.dy558.com/down/rss.php',36,'<c>c%电视%2</c><c>c%连续剧%2</c><c>c%综艺%3</c><c>c%.*?%1</c>','<c>c%国内%1</c><c>c%欧美%2</c><c>c%日韩%3</c><c>c%.*?%0</c>',NULL,'<c>l%.*?%10</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%0</c>','<c>l%.*?%3</c>','<c>l%.*?%3</c>',NULL),
(1,0,'梦幻天堂(论坛)','http://lwgod.com/','http://lwgod.com//rss.php',276,NULL,NULL,NULL,'<c>l%.*?%10</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'飞鸟娱乐(论坛)','http://bbs.hdbird.com/','http://bbs.hdbird.com/rss.php',9,'<c>c%连续剧%2</c><c>c%电影%1</c><c>c%综艺%3</c><c>c%.*?%0</c>',NULL,NULL,'<c>l%.*?%10</c>','<c>c%资源|电影|连续剧%6</c><c>c%.*?%-1</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'中国高清(论坛)','http://www.bt49.com/','http://www.bt49.com/forum.php?mod=rss',17,'<c>c%自主发布|字幕|蓝光|影视|电影|原盘|合集|迅雷%1</c><c>c%美剧|连续剧|纪录片%2</c><c>c%动漫%4</c><c>c%综艺%3</c><c>c%.*?%-1</c>',NULL,'<c>c%高清%5</c><c>l%.*?%4</c>','<c>l%.*?%10</c>','<c>c%碟报%1</c><c>c%评论%2</c><c>c%预告%3</c><c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%3</c>','<c>l%.*?%4</c>',NULL),
(1,0,'很BT电影联盟','http://henbt.com/','http://henbt.com/rss.xml',30,'<c>c%连续剧%2</c><c>c%综艺%3</c><c>c%.*?%1</c>',NULL,NULL,'<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'映像讯','http://mkvcn.com/','http://mkvcn.com/feed',7,'<c>l%.*?%1</c>',NULL,NULL,'<c>l%.*?%5</c>','<c>c%碟报%1</c><c>c%评论%2</c><c>c%脱口秀%7</c><c>c%预告|花絮%3</c><c>c%.*?%1</c>','<c>g%《(.*?)》%1</c><c>g%【(.*?)】%0</c>','<c>l%.*?%2</c>','',NULL),
(1,0,'VeryCD电影','http://www.verycd.com/base/movie/','http://www.verycd.com/base/movie/feed',7,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%3</c>','<c>l%.*?%7</c>','<c>l%.*?%7</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%3</c>',NULL),
(1,0,'VeryCD剧集','http://www.verycd.com/base/tv/','http://www.verycd.com/base/tv/feed',9,'<c>l%.*?%2</c>',NULL,'<c>l%.*?%3</c>','<c>l%.*?%7</c>','<c>l%.*?%7</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%3</c>',NULL),
(1,0,'VeryCD动漫','http://www.verycd.com/base/cartoon/','http://www.verycd.com/base/cartoon/feed',7,'<c>l%.*?%4</c>',NULL,'<c>l%.*?%3</c>','<c>l%.*?%7</c>','<c>l%.*?%7</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%3</c>',NULL),
(1,0,'VeryCD综艺','http://www.verycd.com/base/zongyi/','http://www.verycd.com/base/zongyi/feed',7,'<c>l%.*?%3</c>',NULL,'<c>l%.*?%3</c>','<c>l%.*?%7</c>','<c>l%.*?%7</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%3</c>',NULL),
(1,0,'大连生活网','http://www.dlkoo.com/','http://www.dlkoo.com/down/Rss.xml',6,'<c>c%电影%1</c><c>c%影视%1</c><c>c%电视剧%2</c><c>t%\\[MV\\]%-1</c><c>c%综艺%3</c><c>c%动漫%4</c><c>c%.*?%-1</c>',NULL,'<c>l%.*?%3</c>','<c>l%.*?%0</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'沒有水的魚','http://www.an80.cc/','http://www.an80.cc/feed',37,NULL,NULL,'<c>l%.*?%4</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'第三世界(迅雷)','http://www.mythe3.com/','http://www.mythe3.com/rss.php?fid=16&auth=0',664,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%4</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%0</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'中国高清网','http://www.gaoqing.la','http://www.gaoqing.la/feed',15,'<c>c%series%2</c><c>c%.*?%1</c>',NULL,'<c>c%3d%6</c><c>c%.*?%5</c>','<c>l%.*?%4</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%4</c>',NULL),
(1,0,'电影蜜蜂','http://www.dybee.net/','http://www.dybee.net/feed',54,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%5</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%1</c>','<c>l%.*?%2</c>','<c>l%.*?%4</c>',NULL),
(1,0,'一路电影网','http://www.16movies.cn/','http://www.16movies.cn/feed.xml',29,'<c>c%电影%1</c><c>c%蓝光原盘%1</c><c>l%3D%1</c><c>l%.*?%-1</c>',NULL,'<c>c%1080|蓝光%6</c><c>c%720%5</c><c>c%3D|半宽%7</c><c>l%.*?%4</c>','<c>l%.*?%6</c>','<c>c%电影|大片|蓝光|半宽%6</c><c>c%.*?%-1</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'网易电影频道','http://ent.163.com/','http://ent.163.com/special/00031K7Q/rss_entmovie.xml',27,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'网易电视频道','http://ent.163.com/','http://ent.163.com/special/00031K7Q/rss_enttv.xml',29,'<c>l%.*?%2</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'第三世界(综艺)','http://www.mythe3.com/','http://www.mythe3.com/rss.php?fid=18&auth=0',635,'<c>l%.*?%3</c>',NULL,NULL,'<c>l%.*?%10</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'大片网','http://www.bigpian.cn/','http://www.bigpian.cn/feed',57,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'圣城发布页','http://www.cnscg.org/','http://www.cnscg.org/rss.xml',7,'<c>c%美剧|连续剧%2</c><c>c%.*?%1</c>',NULL,NULL,'<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'老调网','http://www.bestxl.com/','http://www.bestxl.com/rss.php',27,'<c>c%美剧%2</c><c>c%.*?%1</c>',NULL,NULL,'<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'蓝影网','http://www.lanyingwang.com/','http://www.lanyingwang.com/feed',7,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>','1047288328@qq.com'),
(1,0,'天外来客(论坛)','http://girlbt.com/','http://girlbt.com/forum.php?mod=rss&fid=0&auth=0',0,'<c>l%.*?%0</c>',NULL,'<c>c%高清%5</c><c>l%.*?%4</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>','229666956@qq.com '),
(1,0,'寻觅网','http://www.xunmiweb.com/','http://www.xunmiweb.com/feed',41,'<c>l%.*?%1</c>',NULL,NULL,'<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%0</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'无极电影(BT)','http://bbs.btwuji.com/','http://bbs.btwuji.com/rss.php?fid=9',1,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%4</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'无极电影(迅雷)','http://bbs.btwuji.com/','http://bbs.btwuji.com/rss.php?fid=24',1,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%4</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'bloggerlee','http://www.bloggerlee.com/','http://www.bloggerlee.com/?feed=rss2',4,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%2</c>',NULL),
(1,0,'梦千寻影评网','http://jrubbish.com/','http://jrubbish.com/feed',24,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%2</c>',NULL),
(1,0,'VideoClub','http://videoclub.cn/','http://videoclub.cn/feed',0,'<c>c%电影%1</c><c>c%电视%2</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>','waige1986@qq.com'),
(1,0,'量子界','http://www.liangzijie.com/','http://www.liangzijie.com/map-show-id-rss-limit-200.html',0,'<c>l%.*?%0</c>',NULL,'<c>t%高清|超清|3D%5</c><c>l%.*?%-1</c>',NULL,'<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>','liangzimimi@163.com'),
(1,0,'方圈儿','http://www.fangquaner.com/','http://www.fangquaner.com/forum.php?mod=rss&fid=42&auth=0',0,'<c>t%【电影】%1</c><c>t%【剧集】%1</c><c>t%【动漫】%1</c><c>l%.*?%0</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>g%】【(.*?)】%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>','fangquaner@yeah.net'),
(1,0,'zydh123','http://zydh123.net/','http://zydh123.net/rss.php?',0,'<c>l%.*?%0</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%4</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1,0,'3D电影下载','http://www.hoghu.com/','http://www.hoghu.com/feed',1,'<c>c%电影%1</c><c>c%电视%2</c>',NULL,'<c>l%.*?%6</c>','<c>l%.*?%4</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>','mike4668@126.com'),
(1,0,'学习资源网','www.zsvcd.com/','www.zsvcd.com/feed',1,'<c>c%电影%1</c><c>c%电视%2</c><c>l%.*?%-1</c>',NULL,'<c>l%.*?%4</c>','<c>l%.*?%5</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>','kf@888xx.net'),
(1,0,'深影压缩高清(论坛)','http://www.shinybbs.com/','http://www.shinybbs.com/forum.php?mod=rss&fid=62&auth=0',0,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>','327417194@qq.com'),
(1,0,'深影字幕组(论坛)','http://www.shinybbs.com/','http://www.shinybbs.com/forum.php?mod=rss&fid=2&auth=0',0,'<c>l%.*?%1</c>',NULL,NULL,'<c>l%.*?%3</c>','<c>l%.*?%8</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%4</c>','327417194@qq.com'),
(1,0,'射手网(伪)','http://sub.makedie.me/','http://sub.makedie.me/feed.xml',0,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>l%.*?%8</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%4</c>','tomasen@gmail.com'),
(1,0,'SubHD','http://subhd.com/','http://subhd.com/feed',0,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>l%.*?%8</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%4</c>','subhdinfo@gmail.com'),
(1,0,'TLF中文字幕站','http://sub.eastgame.org/','http://sub.eastgame.org/feed',0,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>l%.*?%8</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%4</c>',NULL),
(1,0,'囧夏字幕组','http://blog.jxzmz.org/','http://blog.jxzmz.org/feed/',0,NULL,'<c>l%.*?%3</c>',NULL,'<c>l%.*?%2</c>','<c>l%.*?%8</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%4</c>',NULL),
(1,0,'诸神字幕组','http://i.kamigami.org/','http://i.kamigami.org/feed',0,NULL,'<c>l%.*?%3</c>',NULL,'<c>l%.*?%2</c>','<c>l%.*?%8</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%4</c>',NULL),
(1,0,'电波字幕组','http://dbfansub.com/','http://dbfansub.com/feed/',0,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>l%.*?%8</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%4</c>',NULL),
(1,0,'果然字幕组','http://grzmz.com/','http://grzmz.com/feed/',0,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>l%.*?%8</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%4</c>',NULL),
(1,0,'腾讯电影','http://ent.qq.com/','http://ent.qq.com/movie/rss_movie.xml',0,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%1</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'腾讯电视','http://ent.qq.com/','http://ent.qq.com/tv/rss_tv.xml',0,'<c>l%.*?%2</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%1</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'天堂电影小组','http://group.mtime.com/filmov/','http://feed.mtime.com/group/filmov/topic.rss',0,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'火星360','http://huo360.com/','http://huo360.com/feed',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'豆瓣精彩影评','http://movie.douban.com/review/best/','http://movie.douban.com/feed/review/movie',3,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>x%1%1</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'韩浩月的博客','http://haoyuehan.blog.163.com/','http://haoyuehan.blog.163.com/rss',29,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'苏筱兀的博客','http://my.mtime.com/chencao/','http://feed.mtime.com/my/chencao/feed.rss',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'崔汀的博客','http://blog.sina.com.cn/u/1241252174','http://blog.sina.com.cn/rss/1241252174.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'王玉年的博客','http://blog.sina.com.cn/u/1486481514','http://blog.sina.com.cn/rss/1486481514.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'昆明影视频道','http://blog.sina.com.cn/1831841810','http://blog.sina.com.cn/rss/1831841810.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'影视独舌','http://blog.sina.com.cn/u/3970126254','http://blog.sina.com.cn/rss/3970126254.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'公元1874','http://blog.sina.com.cn/heyan1874','http://blog.sina.com.cn/rss/1734658782.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'黄啸的橙子林','http://blog.sina.com.cn/huangxiaocheng','http://blog.sina.com.cn/rss/1273547187.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'纳兰惊梦','http://blog.sina.com.cn/xjx9755','http://blog.sina.com.cn/rss/1295009824.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'直桃桃淘电影','http://blog.sina.com.cn/qijiuzhiyue','http://blog.sina.com.cn/rss/1407722902.xml',1,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'战台烽','http://blog.sina.com.cn/hezelee','http://blog.sina.com.cn/rss/1120472023.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'电子骑士','http://blog.sina.com.cn/cyberknight001','http://blog.sina.com.cn/rss/1728899515.xml',1,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'陈恺锋博客','http://blog.sina.com.cn/u/1254427453','http://blog.sina.com.cn/rss/1254427453.xml',1,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'娱人愚己','http://blog.sina.com.cn/zengnianqun','http://blog.sina.com.cn/rss/1210402982.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'南都娱乐周刊','http://blog.sina.com.cn/ndzk','http://blog.sina.com.cn/rss/1216431741.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'新华网','http://www.xinhuanet.com/','http://www.xinhuanet.com/ent/news_ent.xml',0,NULL,NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(1,0,'星飞宇部落','http://www.xfyrb.com/','http://www.xfyrb.com/feed',36,'<c>l%movie|yazhuo%1</c><c>l%tv%2</c><c>l%uncategorized%3</c><c>l%.*?%0</c>','<c>l%cn|gt%1</c><c>l%om%2</c><c>l%yazhuo%3</c><c>l%.*?%0</c>','<c>l%.*?%5</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),

(1000,0,'6V电影','http://www.6vhao.com/','http://www.6vhao.com/',4,'<c>c%电影%1</c><c>c%电视剧%2</c><c>l%.*?%-1</c>','<c>c%欧美%2</c><c>c%日韩%3</c><c>c%国产%1</c><c>l%.*?%0</c>','<c>l%.*?%4</c>','<c>l%.*?%2</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'红潮网','http://www.5281520.com/','http://www.5281520.com/',172,'<c>c%电视剧%2</c><c>c%综艺%3</c><c>c%动画片%4</c><c>c%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'ed2000','http://www.ed2000.com/','http://www.ed2000.com/',283,'<c>c%电影%1</c><c>c%剧集%2</c><c>c%动漫%4</c><c>c%综艺%3</c><c>l%.*?%-1</c>',NULL,'<c>l%.*?%4</c>','<c>l%.*?%10</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'飘花资源网','http://www.piaohua.com','http://www.piaohua.com',1102,'<c>c%电视剧%2</c><c>c%电影%1</c>','<c>l%.*?%0</c>','<c>l%.*?%3</c>','<c>l%.*?%2</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'搜磁力链接','http://www.somag.net/','http://www.somag.net/',36,'<c>c%电影%1</c><c>c%动漫%4</c><c>c%3D%1</c><c>c%.*?%2</c>','<c>c%美剧%2</c><c>c%日剧%3</c><c>c%韩剧%3</c><c>c%.*?%0</c>','<c>t%1080p%6</c><c>t%720p%5</c><c>t%HD%5</c><c>c%3D%7</c><c>c%.*?%4</c>','<c>l%.*?%4</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%1</c>','<c>l%.*?%2</c>','',NULL),
(1000,0,'电影天堂','http://www.dy2018.com/','http://www.dy2018.com/',24737,'<c>c%电影%1</c><c>c%电视剧%2</c><c>c%综艺%3</c><c>c%动漫%4</c><c>l%.*?%0</c>','<c>c%华语%1</c><c>c%欧美%2</c><c>c%日韩%3</c><c>c%.*?%0</c>','<c>l%.*?%5</c>','<c>l%.*?%2</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'BT天堂','http://www.bttiantang.com/','http://www.bttiantang.com/',24,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'光影资源联盟','http://www.etdown.net/','http://www.etdown.net/',64,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'高清mp4','http://www.mp4ba.com/','http://www.mp4ba.com/',17,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'电影下载','http://www.dy558.com','http://www.dy558.com',25,NULL,NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'全集网','http://www.quanji.com/','http://www.quanji.com/',1,'<c>l%dianying%1</c><c>l%Dianshiju%2</c><c>l%Zongyijiemu%3</c><c>l%Anime%4</c><c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%10</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'爱磁力','http://www.icili.com','http://www.icili.com',48,'<c>c%电影%1</c><c>c%剧集%2</c><c>c%动漫%4</c><c>c%综艺%3</c><c>l%.*?%-1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%5</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'阳光电影','http://www.ygdy8.net/','http://www.ygdy8.net/',5,'<c>l%zongyi%3</c><c>l%dongman%4</c><c>l%tv%2</c><c>l%dy|movie%1</c><c>l%.*?%-1</c>','<c>l%\\/hytv\\/%1</c><c>l%\\/rihantv\\/%3</c><c>l%\\/oumeitv\\/%2</c><c>t%中国|香港|台湾|大陆|澳门%1</c><c>t%欧美|美国|欧洲|俄罗斯|英国|法国|德国%2</c><c>t%日本|韩国%3</c><c>l%.*?%0</c>','<c>t%TC|TS|抢先%1</c><c>l%\\/3d\\/%6</c><c>t%DVD%3</c><c>t%BD|1280|高清|HD%4</c><c>l%.*?%3</c>','<c>l%.*?%1</c>','<c>l%.*?%6</c>','<c>g%《(.*?)》%1</c><c>g%(.*?)-20%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'66BT','http://www.66bt.cc','http://www.66bt.cc',11,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(1000,0,'思享','http://www.vvtor.com','http://www.vvtor.com',2,'<c>l%.*?%1</c>',NULL,'<c>l%.*?%5</c>','<c>l%.*?%3</c>','<c>l%.*?%6</c>','<c>x%1%1</c>','<c>l%.*?%2</c>','<c>l%.*?%3</c>',NULL),
(2000,0,'格瓦拉活动','http://www.gewara.com/activity/','http://www.gewara.com/activity/',16,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%4</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'时光网短频','http://www.mtime.com/trailer','http://www.mtime.com',4,'<c>l%.*?%0</c>',NULL,NULL,'<c>l%.*?%7</c>','<c>l%.*?%3</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'大众影评网','http://www.51oscar.com','http://www.51oscar.com',6,'<c>c%电影%1</c><c>c%电视%1</c>',NULL,NULL,NULL,'<c>c%资讯%1</c><c>c%影评%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'时光网预告','http://www.mtime.com/trailer/trailer/index.html','http://www.mtime.com/trailer/trailer/index.html',8,NULL,NULL,NULL,'<c>l%.*?%7</c>','<c>l%.*?%3</c>','<c>g%《(.*?)》%0</c>',NULL,NULL,NULL),
(2000,0,'时光网特约评论','http://www.mtime.com/review/column/','http://www.mtime.com/review/column/',0,'<c>c%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'凤凰网娱乐','http://ent.ifeng.com','http://ent.ifeng.com',45,NULL,NULL,NULL,NULL,'<c>c%资讯%1</c><c>c%评论%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'网易娱乐','http://ent.163.com','http://ent.163.com',962,'<c>c%电影%1</c><c>c%电视%2</c><c>c%综艺%3</c>','<c>c%华语|港台%1</c><c>c%欧美日韩%0</c><c>c%海外|欧美%2</c><c>c%日韩%3</c><c>c%.*?%0</c>',NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'新浪评论','http://ent.sina.com.cn/review/','http://ent.sina.com.cn/review/',8,'<c>c%电影%1</c><c>c%电视%2</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%2</c>',NULL),
(2000,0,'搜狐娱乐','http://yule.sohu.com','http://yule.sohu.com',9,'<c>c%电影%1</c><c>c%电视%2</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'时光网新闻','http://news.mtime.com','http://news.mtime.com',216,'<c>c%电影%1</c><c>c%电视%2</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%1</c><c>g%`(.*?)`%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'时光网评论','http://www.mtime.com/top/blog/hot_24h/','http://www.mtime.com/top/blog/hot_24h/',32,'<c>c%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%2</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%2</c>',NULL),
(2000,0,'海上电影','http://www.sfs-cn.com/','http://www.sfs-cn.com/',3,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(2000,0,'格瓦拉影讯','http://www.gewara.com/news/cinema','http://www.gewara.com',36,'<c>l%.*?%1</c>',NULL,NULL,NULL,'<c>l%.*?%1</c>','<c>g%《(.*?)》%0</c>',NULL,'<c>l%.*?%1</c>',NULL),
(9999,0,'预告片世界','http://www.yugaopian.com','http://www.yugaopian.com/rss.xml',0,'<c>l%.*?%1</c>',NULL,NULL,'<c>l%.*?%7</c>','<c>l%.*?%3</c>','<c>g%(.*?) \\(%1</c><c>g% \\((.*?)\\)%1</c><c>g%(.*?) 预告片%1</c><c>g%(.*?) 先行版%1</c><c>g%(.*?) 剧场版%1</c>',NULL,NULL,NULL),
(9999,0,'电影FM','http://www.dianying.fm','http://www.dianying.fm',0,'<c>l%.*?%0</c>',NULL,NULL,'<c>l%.*?%4</c>','<c>l%.*?%6</c>','<c>g%(.*?)\\(%1</c>','<c>l%.*?%2</c>',NULL,NULL),
(9999,0,'豆瓣预告','http://www.douban.com','http://www.douban.com',0,'<c>l%.*?%0</c>',NULL,NULL,'<c>l%.*?%7</c>','<c>l%.*?%3</c>','<c>g%《(.*?)》%0</c>',NULL,NULL,NULL),
(9999,0,'m1905购票','http://www.1905.com/video/play/','http://www.1905.com/video/play/',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(9999,0,'m1905预告花絮','http://www.1905.com/','http://www.1905.com/',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(9999,0,'格瓦拉预告花絮','http://www.gewara.com/movie/','http://www.gewara.com/movie/',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(9999,0,'格瓦拉购票','http://www.gewara.com/','http://www.gewara.com/',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


/*!40000 ALTER TABLE `author` ENABLE KEYS */;
